In [1]:
#builtin
import os , warnings

#data
import pandas as pd
import numpy as np

#metrics
from sklearn.metrics import roc_curve , auc , confusion_matrix

#preprocessing
from sklearn.preprocessing import LabelEncoder

#estimator
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

#model selection
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

#visualisation
import matplotlib.pyplot as plt

In [2]:
os.listdir()

['.ipynb_checkpoints', 'data', 'Modelisation.ipynb', 'Nettoyage data.ipynb']

In [3]:
data = pd.read_csv('data/cleaned/df_cleaned.csv')

data.head()

target  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0       1          5            2          4        1     6                1   
1       0          5            2          9        1     0                1   
2       0          0            2          8        1     3                1   
3       1          5            3          8        1     6                1   
4       0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-above-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-surface-below-ring  stalk-color-above-ring  stalk-color-below-ring  \
0                         2                       7                       7   
1                         2                       7                       7   
2                         2                       7                       7   
3                         2                       7                       7   
4                         2                       7                       7   

   veil-color  ring-number  ring-type  spore-print-color  population  habitat  
0           2            1          4                  2           3        5  
1           2            1          4                  3           2        1  
2           2            1          4                  3           2        3  
3           2            1          4                  2           3        5  
4           2            1          0                  3           0        1  

[5 rows x 22 columns]

In [4]:
X = data.drop(columns='target')
X

cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0             5            2          4        1     6                1   
1             5            2          9        1     0                1   
2             0            2          8        1     3                1   
3             5            3          8        1     6                1   
4             5            2          3        0     5                1   
...         ...          ...        ...      ...   ...              ...   
8119          3            2          4        0     5                0   
8120          5            2          4        0     5                0   
8121          2            2          4        0     5                0   
8122          3            3          4        0     8                1   
8123          5            2          4        0     5                0   

      gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0                0          1           4            0  ...   
1                0          0           4            0  ...   
2                0          0           5            0  ...   
3                0          1           5            0  ...   
4                1          0           4            1  ...   
...            ...        ...         ...          ...  ...   
8119             0          0          11            0  ...   
8120             0          0          11            0  ...   
8121             0          0           5            0  ...   
8122             0          1           0            1  ...   
8123             0          0          11            0  ...   

      stalk-surface-above-ring  stalk-surface-below-ring  \
0                            2                         2   
1                            2                         2   
2                            2                         2   
3                            2                         2   
4                            2                         2   
...                        ...                       ...   
8119                         2                         2   
8120                         2                         2   
8121                         2                         2   
8122                         2                         1   
8123                         2                         2   

      stalk-color-above-ring  stalk-color-below-ring  veil-color  ring-number  \
0                          7                       7           2            1   
1                          7                       7           2            1   
2                          7                       7           2            1   
3                          7                       7           2            1   
4                          7                       7           2            1   
...                      ...                     ...         ...          ...   
8119                       5                       5           1            1   
8120                       5                       5           0            1   
8121                       5                       5           1            1   
8122                       7                       7           2            1   
8123                       5                       5           1            1   

      ring-type  spore-print-color  population  habitat  
0             4                  2           3        5  
1             4                  3           2        1  
2             4                  3           2        3  
3             4                  2           3        5  
4             0                  3           0        1  
...         ...                ...         ...      ...  
8119          4                  0           1        2  
8120          4                  0           4        2  
8121          4                  0           1        2  
8122          0                  7           4        2  
8123          4 

In [5]:
y = data['target']
y

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: target, Length: 8124, dtype: int64

In [6]:
x_train , x_test , y_train , y_test = train_test_split(X , y ,
                                                       test_size = 0.3 ,
                                                       random_state = 42
)

In [7]:
print("Nos données d'entrainement sont sous la forme ", x_train.shape," et les predictions sont sous la forme ", y_train.shape)
print("Nos données de tests sont sous la forme ", x_test.shape," et les predictions sont sous la forme ", y_test.shape)

Nos données d'entrainement sont sous la forme  (5686, 21)  et les predictions sont sous la forme  (5686,)
Nos données de tests sont sous la forme  (2438, 21)  et les predictions sont sous la forme  (2438,)


In [8]:
#Modelisation , base line

estimator = DummyClassifier(strategy = 'most_frequent')
estimator.fit(x_train,y_train)

DummyClassifier(strategy='most_frequent')

In [9]:
y_pred = estimator.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [10]:
pd.Series(y_pred).value_counts()

0    2438
Name: count, dtype: int64

In [11]:
y_test.value_counts(normalize = True).round(4)

target
0    0.5156
1    0.4844
Name: proportion, dtype: float64

In [12]:
print("Score train ", estimator.score(x_train , y_train).round(4))
print("Score test ", estimator.score(x_test , y_test).round(4))

Score train  0.519
Score test  0.5156


In [13]:
def score(estimator) :
    print("Score train ", estimator.score(x_train , y_train).round(4))
    print("Score test ", estimator.score(x_test , y_test).round(4))

In [14]:
y_train.value_counts(normalize = True).round(4)

target
0    0.519
1    0.481
Name: proportion, dtype: float64

In [15]:
score(estimator)

Score train  0.519
Score test  0.5156


In [16]:
mat = confusion_matrix(y_test , y_pred)
mat

array([[1257,    0],
       [1181,    0]], dtype=int64)

In [17]:
mat = pd.DataFrame(mat)
mat.rename(columns={0 : 'pred_0' , 1 : 'pred_1'} , inplace = True)
mat.index = [f"test_{i}" for i in mat.index]
mat

pred_0  pred_1
test_0    1257       0
test_1    1181       0

In [18]:
def confusion(y_test , y_pred) :
    mat = confusion_matrix(y_test , y_pred)
    mat = pd.DataFrame(mat)
    
    for col in mat.columns :
        mat.rename(columns={col : f'pred_{col}'} , inplace = True)
        
    mat.index = [f"test_{i}" for i in mat.index]
    
    return mat

In [19]:
confusion(y_test , y_pred)

pred_0  pred_1
test_0    1257       0
test_1    1181       0

In [20]:
false_positive_rate , true_positive_rate , thresholds = roc_curve(y_test , y_pred)
roc_auc = auc(false_positive_rate , true_positive_rate)
roc_auc

0.5

In [22]:
#Modelisation Régression Logistique

estimator = LogisticRegression(solver='liblinear')
estimator.fit(x_train , y_train)

LogisticRegression(solver='liblinear')

In [24]:
y_pred = estimator.predict(x_test)
y_pred

array([0, 1, 1, ..., 1, 0, 0], dtype=int64)

In [25]:
y_proba = estimator.predict_proba(x_test).round(2)
y_proba

array([[1.  , 0.  ],
       [0.09, 0.91],
       [0.  , 1.  ],
       ...,
       [0.09, 0.91],
       [1.  , 0.  ],
       [0.96, 0.04]])

In [26]:
score(estimator)
confusion(y_test , y_pred)

Score train  0.9488
Score test  0.9491


pred_0  pred_1
test_0    1201      56
test_1      68    1113

In [27]:
false_positive_rate , true_positive_rate , thresholds = roc_curve(y_test , y_pred)
roc_auc = auc(false_positive_rate , true_positive_rate)
roc_auc

0.9489355797205421

In [28]:
# Modelisation SVM

estimator = LinearSVC()
estimator.fit(x_train , y_train)

C:\Users\CHARLOT\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\CHARLOT\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [29]:
y_pred = estimator.predict(x_test)
y_pred

array([0, 1, 1, ..., 1, 0, 0], dtype=int64)

In [30]:
score(estimator)
confusion(y_test , y_pred)

Score train  0.9523
Score test  0.9495


pred_0  pred_1
test_0    1198      59
test_1      64    1117

In [31]:
false_positive_rate , true_positive_rate , thresholds = roc_curve(y_test , y_pred)
roc_auc = auc(false_positive_rate , true_positive_rate)
roc_auc

0.9494357423997166