In [7]:
import numpy as np

liste = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]

revenus = np.array(liste)

revenus

array([1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300])

In [2]:
haut_revenus = revenus[revenus > 3000]

haut_revenus

array([5000])

In [8]:
somme = revenus.sum() * 12
somme

248064

In [9]:
moyenne = somme // 10

moyenne

24806

In [10]:
revenus[revenus == 1400] += 200

revenus

array([1800, 1500, 2200, 3000, 2172, 5000, 1600, 1200, 1100, 1300])